### ISSUE TITLE
Roadmap Telegram

### ISSUE THREAD

**Issue by ledamint** [urban-bot/urban-bot#91]
- [ ] [Inline query](https://core.telegram.org/bots/api#inline-mode) - 3d
- [x] Allow to add a proxy - 3h
To bypass internet provider blocking.
- [ ] download files util - 3h
If a user sends an image, video, or file, allow to easily download it.

```javascript
// Something like:
function Component() {
    useImage((event) => {
        download(filePath, event);
    });
    // ...
}
```
- [ ] fix node-telegram-bot-api types - 1d
You can find them in code `@types/node-telegram-bot-api bug`
- [x] add resize_keyboard prop - 1h
