### ISSUE TITLE
Roadmap Facebook

### ISSUE THREAD

**Issue by ledamint** [urban-bot/urban-bot#93]
- [ ] senf files as buffer or stream - 4h
- [ ] fb media https://developers.facebook.com/docs/messenger-platform/send-messages/template/media - 2h
- [ ] fb order https://developers.facebook.com/docs/messenger-platform/send-messages/template/receipt - 2h
- [ ] fb sender action https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions - 2h
- [ ] fb sticker - 1h
